
text0 = "I ALWAYS FEEL LIKE OTHERS ARE MIRORS";
text1 = "IN FRONT OF WHICH I'M DANCING GROTESQUELY";
text2 = "IF I ADMIRE MY FACE, MY SHOULDERS, MY ARMS, MY FLANKS";
text3 = "AGAIN I REPLY TO MYSELF THIS IS NOT MY FAULT";

event_inherited();

walk_spd = 2;
jump_spd = -20;
