
text0 = "GENDER STEREOTYPES MAKE ME WANT TO KILL MYSELF";
text1 = "I'VE BEEN THINKING ABOUT THIS FOR QUITE A WHILE BUT...";
text2 = "THERE IS SOMETHING DEEPLY WRONG ABOUT IT";
text3 = "THESE THINGS ASTONISH ME BEYOND WORDS.";

event_inherited();

walk_spd = 2;
jump_spd = -20;
