
text0 = "THEY ARE SO COOL, SO DRUNK WITH THEIR SMART BIG SMILES";
text1 = "AND I TALK TO THEM IN MY SECRET MIND OF PURE LONELINESS";
text2 = "AND NO ONE KNOWS WETHER I THINK GOOD OR EVIL";
text3 = "I AM HELPLESS";

event_inherited();

walk_spd = 3;
jump_spd = -15;
